{{- $apiVersion := include "imgproxy.versions.ingress" . }}
{{- with .Values.resources.ingress }}
{{- if (.enabled | and $apiVersion) }}
---
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "imgproxy.fullname" $ }}
  labels:
    app: {{ template "imgproxy.fullname" $ }}
    chart: {{ template "imgproxy.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    imgproxy: "true"
    <<: {{ $.Values.resources.common.labels | default dict | toYaml | nindent 6 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .className }}
  ingressClassName: {{ .className | quote }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- $pathType := .pathType | default "ImplementationSpecific" }}
  rules:
    {{- range .hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- $name := include "imgproxy.fullname" $ }}
          {{- $path := default "/" $.Values.features.server.pathPrefix }}
          {{- if eq $apiVersion "networking.k8s.io/v1" }}
          - path: {{ $path | quote }}
            pathType: {{ $pathType | quote }}
            backend:
              service:
                name: {{ $name | quote }}
                port:
                  number: 80
          {{- else }}
          - path: {{ $path | quote }}
            backend:
              serviceName: {{ $name | quote }}
              servicePort: 80
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
