name: release-helm-chart
on:
  push:
    tags:
    - *
jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: imgproxy-helm/
    - uses: actions/checkout@v2
      with:
        path: helm-repository/
        ref: gh-pages
    - uses: azure/setup-helm@v1
    - name: Pack the current chart version
      run: helm package -d helm-repository/ imgproxy-helm/imgproxy/
    - name: Reindex Helm repository
      run: helm repo index --url https://helm.imgproxy.net/ --merge helm-repository/index.yaml helm-repository/
    - name: Commit & Push gh-pages with a new chart
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        cd helm-repository/
        git add .
        git commit -m "${GITHUB_REF##*/} release"
        git push origin gh-pages
